<h1> <center> Taller de análisis y visualización de datos con R </center> </h1>

<h2> <center>  1. Introducción a la programación con R (1) </center> </h2>

<!-- <h3> <center> Jorge Castro - jcastro@cenat.ac.cr </center> </h3>
<h3> <center> Diego Jiménez - djimenez@cenat.ac.cr </center> </h3> -->



 <table>  
  <tr>
    <td><h3>Jorge Castro</h3></td>
    <td><h3>jcastro@cenat.ac.cr</h3></td>
  </tr>  
  <tr>
    <td><h3>Diego Jiménez</h3></td>
    <td><h3>djimenez@cenat.ac.cr</h3></td>
  </tr> 
</table>

<table>  
  <tr>
    <td> <img align="left" src="img/cnca.png", width=400></td>
    <td> <img align="right" src="img/cenat.png", width=400></td>
  </tr>  
  <tr>
    <td colspan="2"> <center> <h3> Octubre 2017 </h3> </center> </td>
  </tr>  
</table>



# Contenido

1. [Conceptos de programación](#conceptos)
    - [Algoritmos](#algoritmos)
    - [Variables](#variables)
    - [Estructuras de control](#estructurasC)
    - [Ciclos](#ciclos)
    - [Estructuras de datos](#estructurasD)
<br><br>
2. [Estructuras de datos en R](#estructurasDR)
    - [Vectores](#vectores)
    - [Vectores multidimensionales](#matrices) 
    - [Listas](#listas)
    - [Marcos de datos (Data Frames)](#marcos)
<br><br>
3. [Funciones](#funciones)
<br><br>
4. [Ejercicios](#ejercicios)

<a id='conceptos'></a>
<hr>
<hr>
<h1><center><span style="color:blue">Conceptos de programación</span></center></h1>
<hr>
<hr>

# Definición de algoritmo <a id='algoritmos'></a>

<!-- <img style="float:right;" src="img/alkawa.png", width=120, caption="Muhammad ibn Mūsā al-Khwārizmī"> -->
 <figure style="float:right;">
  <img  src="img/alkawa.png", width=120>
  <figcaption>Muhammad ibn Mūsā al-Khwārizmī</figcaption>
</figure> 


- Un algoritmo es un conjunto
    -  Ordenado
    -  Finito
- Cuyos elementos (instrucciones) son
    -  Finitos
    -  Bien especificados (no ambiguos)
- Ejecutado por un agente que <b>no</b> requiere de ingenio

 

# Representación de algoritmos

Los algoritmos se pueden escribir de diversas formas:
- En lenguaje “natural”, con expresiones comunes
    - 1 Tomar dos números enteros
    - 2 Sumarlos
    - 3 Escribir el resultado al final de la página
- En lenguaje formal, con símbolos matemáticos
    - 1 Sean $a,b \in \mathbb{Z}$
    - 2 $c = a + b$
    - 3 El resultado es c


¿Por qué es preferible usar sı́mbolos matemáticos?

# Elementos de un algoritmo

- Instrucciones: indican qué hacer en un momento dado
    - “Mostrar valor en pantalla”
    - “Guardar archivo”
- Variables: contenedores, su valor puede cambiar con el tiempo
    - a =1
    - b = 2,5
- Operadores: transforman o modifican expresiones
    - Asignación: =
    - Aritméticos: +, -, /, *, %
    - Comparación: >, <, >=, <=, ==, !=
    - Lógicos: ||, &&, ! (equivalentes a ∨, ∧, ¬ respectivamente)
- Estructuras de control: alteran la secuencia de instrucciones
    - Decisiones y ciclos
- Estructuras de datos: organizan y relacionan conjuntos de variables
    - Arreglos, listas, conjuntos, árboles, diccionarios ...

# Variables <a id='variables'></a>

- Representan valores de diversos tipos
- Poseen:
    - Nombre
    - Valor
    - Direcciòn, tipo y tamaño
- Ejemplo:
    - nombre = “Bruce”
    - profesión = “Batman”
    - edad = 33
    - x = ’g’
    - y = 3,14159265359
    - arreglo = 1, 2, 3
- En programación, las variables debe ser declaradas e inicializadas.

In [1]:
# numeric
varNumerica <- 2.6
is.numeric(varNumerica) #true

# integer
varEntera <- as.integer(3)
is.integer(varEntera) #true

# complex
varCompleja = 1 + 2i

# logical
varLogica <- TRUE
is.numeric(varLogica) #false

# character
varCaracter <- "p"
varCaracter2 <- "hola"
is.character(varCaracter) #true

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

# Condicional <a id='estructurasC'></a>

- Estructura de control que realizan una secuencia de instrucciones sólo si se cumple una condición.
- Por ejemplo:
Un juego de escudo y corona se rige por la regla: “Si sale lo que escogı́, entonces gano; sino, entonces pierdo.”

<img src="img/conditional.png", width=400>

In [5]:
escogencia = "escudo"
moneda= "corona"

if(escogencia == moneda){
    print("gane")
} else {
    print("perdi")
}


[1] "perdi"


# Ciclos <a id='ciclos'></a>

- Repiten una secuencia de instrucciones muchas veces en forma implı́cita
    - Verifican condiciones para decidir si seguir repitiendo o detenerse
    - La condición de parada puede ser el cumplimiento exitoso de N ciclos
    - Plantean repeticiones en forma iterativa.
- Por ejemplo, una estructura matemática iterativa es la sumatoria:
<br>
<br>
<center> $\sum _{i=1}^{10} i = 1 + 2 + \ldots + 9 + 10$ </center>

# Mientras (while)

<figure style="float:right;">
  <img  src="img/while.png", width=250>
</figure> 




- Prueba lógica
- Ejecución del cuerpo del ciclo
- Se itera hasta que la prueba sea **FALSA**

# Ejemplo con estructuras de control

<hr>
**Algoritmo 1** Imprimir en pantalla los números del 1 al 10
<hr>
```fortran
1. function IMPRIMIR
2.    x = 1
3.    while x <= 10 do
4.       imprimir x
5.       x = x + 1 (*)
6.       end while
7. end function
```
<hr>

(*) Conceptos importantes: acumuladores y cambio de valor

In [9]:
# Mientras en R (while)
x <- 7
while(x <= 15) {
    print(x)
    x <- x+2
}

[1] 7
[1] 9
[1] 11
[1] 13
[1] 15


# Para (for)

<figure style="float:right;">
  <img  src="img/for.png", width=250>
</figure>

- Se itera una cantidad determinada de
veces
- Se ejecuta el cuerpo del ciclo

In [10]:
arreglo <- 1:10
for(a in arreglo)
{
print(a)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


# Estructuras de Datos <a id='estructurasD'></a>

- Las estructuras de datos organizan y facilitan la lectura, manipulación y relación de valores
- El tipo más básico es el arreglo (vector)
<br><br>
<img src="img/EdD.png", width=800>


<a id='estructurasDR'></a>
<hr>
<hr>
<h1><center><span style="color:blue">Estructuras de datos en R</span></center></h1>
<hr>
<hr>

In [11]:
?array

In [12]:
?array

# Vectores <a id='vectores'></a>

- Una variable que contiene múltiples valores del mismo tipo en una estructura de una dimensión.
- La función c() permite hacer vectores al concatenar varios valores.

In [ ]:
#Vectores en R

x <- c(T,F)
x <- c(1,2,3,4)
x <- c(0.5,0.6)
x <- c(1+0i,2+4i)
x <- c("a","b","c","de")

- Todos los elementos de un vector deben ser del mismo tipo, de lo contrario R forzará todos los elementos al tipo más genérico
- Este comportamiento se llama coerción y R lo aplica automáticamente cuando existe ambigüedad entre los datos 

In [13]:
#Coerción en R

x <- c( 1 , 0.5 , 10 ) # Tipo numérico
y <- c( 1 , 1+3i , 0.5 ) # Tipo complejo
z <- c( 1 , "hola" , 2+1i ) # Tipo texto

- Se pueden crear vectores a partir de secuencias numéricas
- También se pueden crear vectores vacı́os de tamaño predeterminado

In [22]:
# Secuencias con incrementos de 1
x <- 1:10 # 1,2,3,...,10
x <- 5:23 # 5,6,7,...,23
x <- 10:1 # 10,9,8,...,1
x <- 0.5:2.8 # 0.5,1.5,2.5

# Secuencias con incrementos variables
x <- seq(1,10,2) # 1,3,5,7,9
x <- seq(2,10,2) # 2,4,6,8,10

# Vectores vacíos
x <- vector("numeric",length=10) # 0,0,0,0,0,0,0,0,0,0
x <- vector("character",length=3) # "","",""
x
z <- vector("character",3) # "","",""
z
?vector

[1] "" "" ""

[1] "" "" ""

- Para consultar valores de un vector se usa el operador subı́ndice [ ]
- $x[i]$ hace referencia al i-ésimo elemento de $x$
- El operador [ ] también se puede usar para asignar valores a una variable

In [27]:
x <- c(10,20,25,30)
x[5]       # Extracción del primer elemento
x[7] <- 15 # Asignación del primer elemento
x[5]
x

[1] NA

[1] NA

[1] 10 20 25 30 NA NA 15

# Matrices <a id='matrices'></a>

- Una matriz es un vector de dos dimensiones
- Se puede crear con la función *matrix()* que recibe como primer parámetro un vector cualquiera y los parámetros por nombre nrow y ncol.

In [39]:
m <- matrix(1:6,nrow=3,ncol=2)
m
#m[1,2] # Extracción de un elemento por fila y columna
#m[2,]  # Extracción de una fila completa
m[,1]  # Extracción de una columna completa

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] 1 2 3

- Si el vector de entrada tiene más elementos de los que puede tener la matriz, los elementos que se desbordan son descartados
- Si tiene menos elementos, se repiten los primeros en orden hasta llenar los espacios faltantes

In [41]:
#m <- matrix(1:8,nrow=2,ncol=2)
#m
m2 <- matrix(1:8,nrow=4,ncol=4)
m2

[,1] [,2] [,3] [,4]
[1,] 1    5    1    5   
[2,] 2    6    2    6   
[3,] 3    7    3    7   
[4,] 4    8    4    8

# Arreglos <a id='arreglos'></a>

- Un arreglo es un vector de varias dimensiones
- Recibe como parámetros:
    - Vector de datos
    - Vector de enteros que indican el tamaño de cada dimensión
- Por ejemplo si este vector es de tamaño 3 se crea un 'cubo' de datos

In [46]:
a <- array(1:48,dim=c(4,4,3))
#a
#a[1,1,1] # Extracción de un único elemento
#a[2,,1]  # Extracción de una única fila
a[,,1]   # Extracción de una capa (submatriz)

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

# Listas <a id='listas'></a>

- A diferencia de los vectores:
    - Las listas pueden tener elementos de distintos tipos (R no aplica coerción)
    - El operador $[i]$ retorna una lista de tamaño 1 con el elemento deseado
- Para extraer un elemento (al igual que en un vector) se usa el operador $[[i]]$

In [50]:
# Listas en R

x <- list(1,"a",T,1.3)

x # Impresión de la lista en pantalla 

x[2] # Extracción de una sublista

x[[2]] # Extracción de un elemento

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1.3

[[1]]
[1] "a"

[1] "a"

# Marcos de datos (Data Frames) <a id='marcos'></a>

- Estructura de dos dimensiones en la cual cada columna tiene su propio tipo de datos
- Las columnas en un marco de datos pueden tener etiquetas que permiten al usuario consultarlas con mayor facilidad usando el sı́mbolo $
- Al consultar una columna por su etiqueta, se obtiene un vector

In [56]:
# Marco de datos en R
a <- c(1,2,3)
b <- c("X","Y","Z")
c <- c(T,T,F)
f <- data.frame(ColA = a, ColB = b, ColC = c)
f
#f$ColA
as.data.frame(f$ColA) 

ColA ColB ColC 
1 1    X     TRUE
2 2    Y     TRUE
3 3    Z    FALSE

f$ColA
1 1     
2 2     
3 3

- Al igual que los vectores, los elementos en un marco de datos pueden ser consultados con el operador [i,j]

- Al ser una estructura bidimensional siempre hay que indicar las dos dimensiones, aunque puede dejarse una vacı́a si se quiere recuperar toda una fila o una columna (i.e.: [i,] o [,i])

- Las filas también pueden tener etiquetas, y al consultar un valor con el operador [i,i] puede usarse la etiqueta de la fila o columna en lugar de su ı́ndice


In [59]:
row.names(f) <- c("F1","F2","F3")
f[1,1] # Consulta del elemento en la fila 1, columna 1

f["F1","ColB"] # Consulta del elemento en la fila F1 (1), columna ColA (1)

[1] 1

[1] X
Levels: X Y Z

<a id='funciones'></a>
<hr>
<hr>
<h1><center><span style="color:blue">Funciones </span></center></h1>
<hr>
<hr>

# Funciones

- Agrupan instrucciones que resuelven tareas específicas
- Ayudan a modularizar el problema
- Permiten construir soluciones complejas mediante elementos sencillos
- Reciben algún tipo de entrada, la transforman o manipulan y retornan el resultado
- Pueden ser utilizadas dentro de otras funciones.
- Pueden combinarse con otras funciones.
    - Principio de composición funcional:  $f(g(x))$


# Ejemplo de función

Objetivo: verificar si un número está en una lista
Sean $L$ una lista de números, y $n$ el elemento buscado

<hr>
**Algoritmo 2** Búsqueda en una lista
<hr>
```fortran
1. function ESTAEN(L, n)
2.    for e|emento en L do
3.       if e|emento == n then
4.          Retornar VERDADERO
5.       end if
6.    end for
7.    Retornar FALSO
8. end function
```
<hr>



In [68]:
#Ejemplo de función en R

buscarPosicion <- function(L, n) {
    i <- 1
    for(elemento in L) {
        if(elemento == n) {
            return(i)
        }
        i = i+1
    }
    return(-1)
}

miLista <- c(2 , 8 , 7, 3 , 3)
elemBuscado <- 3
resultado <- buscarPosicion(miLista, elemBuscado)
resultado

[1] 4

<a id='ejercicios'></a>
<hr>
<hr>
<h1><center><span style="color:blue">Ejercicios de programación</span></center></h1>
<hr>
<hr>

Resuelva los ejercicios del notebook: "Ejercicios_intro_programacion_R.ipynb"